[package]
name = "iced-demo"
version.workspace = true
edition.workspace = true

[dependencies]
iced = { git = "https://github.com/iced-rs/iced", rev = "169667ef1b4fa754ed1edb5fa0e845aede2638fb", features = [
    "canvas",
] }
lilt = { path = "../.." }
iced_futures = "0.12.0"
