name: "Snapshot Commit"

on:
  issue_comment:
    types: [created]

permissions:
  issues: read
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  snapshot:
    if: ${{ github.event.comment.body == 'snapshot' && github.event.issue.pull_request }}
    runs-on: ubuntu-latest

    steps:
      - name: Check if comment author is a collaborator
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euxo pipefail

          AUTHOR="${{ github.actor }}"
          REPO="${{ github.repository }}"

          # Call the API and capture headers
          RESPONSE=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            --include \
            /repos/$REPO/collaborators/$AUTHOR)

          # Extract the HTTP status code from the response headers
          STATUS=$(echo "$RESPONSE" | grep HTTP | awk '{print $2}')

          if [[ "$STATUS" != "204" ]]; then
            echo "Unauthorized user: $AUTHOR"
            exit 1
          fi

      - name: Checkout pull request 🏁
        uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head

      - name: Insta
        run: |
          set -euxo pipefail

          cargo install cargo-insta
          cargo insta test --features test-api
          cargo insta accept

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add src/snapshots/
          git commit -m "[bot] Update snapshots"
          git push
